### ISSUE TITLE
Error during cleanup

### ISSUE THREAD

**Issue by simonklb** [juju-solutions/charm-flannel#25]
```
unit-flannel-3: 09:06:03 INFO unit.flannel/3.juju-log Reactive main running for hook stop
unit-flannel-3: 09:06:03 INFO unit.flannel/3.juju-log Invoking reactive handler: reactive/flannel.py:190:cleanup_deployment
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop Failed to stop flannel.service: Unit flannel.service not loaded.
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop Cannot find device "flannel.1"
unit-flannel-3: 09:06:03 INFO unit.flannel/3.juju-log Unable to remove iface flannel.1
unit-flannel-3: 09:06:03 INFO unit.flannel/3.juju-log Potential indication that cleanup is not possible
unit-flannel-3: 09:06:03 INFO unit.flannel/3.juju-log Invoking reactive handler: reactive/flannel.py:167:ready
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop Traceback (most recent call last):
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop   File "/var/lib/juju/agents/unit-flannel-3/charm/hooks/stop", line 19, in <module>
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop     main()
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop     bus.dispatch()
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop     _invoke(other_handlers)
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop     handler.invoke()
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop     self._action(*args)
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop   File "/var/lib/juju/agents/unit-flannel-3/charm/reactive/flannel.py", line 171, in ready
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop     status_set('active', 'Flannel subnet ' + get_flannel_subnet())
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop   File "/var/lib/juju/agents/unit-flannel-3/charm/reactive/flannel.py", line 223, in get_flannel_subnet
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop     with open('/run/flannel/subnet.env') as f:
unit-flannel-3: 09:06:03 INFO unit.flannel/3.stop FileNotFoundError: [Errno 2] No such file or directory: '/run/flannel/subnet.env'
unit-flannel-3: 09:06:03 ERROR juju.worker.uniter.operation hook "stop" failed: exit status 1
```

**Comment by rimusz** [comment]
rebooted k8s master and got flannel error:
```
kubernetes-master/0*  active    idle   0        1.2.3.4    6443/tcp        Kubernetes master running.
  flannel/1           error     idle            1.2.3.4                    hook failed: "leader-settings-changed"
```
debug log:
```
$ juju debug-log --include unit-flannel-1
unit-flannel-1: 15:32:03 INFO unit.flannel/1.leader-settings-changed     handler.invoke()
unit-flannel-1: 15:32:03 INFO unit.flannel/1.leader-settings-changed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
unit-flannel-1: 15:32:03 INFO unit.flannel/1.leader-settings-changed     self._action(*args)
unit-flannel-1: 15:32:03 INFO unit.flannel/1.leader-settings-changed   File "/var/lib/juju/agents/unit-flannel-1/charm/reactive/flannel.py", line 171, in ready
unit-flannel-1: 15:32:03 INFO unit.flannel/1.leader-settings-changed     status_set('active', 'Flannel subnet ' + get_flannel_subnet())
unit-flannel-1: 15:32:03 INFO unit.flannel/1.leader-settings-changed   File "/var/lib/juju/agents/unit-flannel-1/charm/reactive/flannel.py", line 223, in get_flannel_subnet
unit-flannel-1: 15:32:03 INFO unit.flannel/1.leader-settings-changed     with open('/run/flannel/subnet.env') as f:
unit-flannel-1: 15:32:03 INFO unit.flannel/1.leader-settings-changed FileNotFoundError: [Errno 2] No such file or directory: '/run/flannel/subnet.env'
unit-flannel-1: 15:32:03 ERROR juju.worker.uniter.operation hook "leader-settings-changed" failed: exit status 1
unit-flannel-1: 15:32:03 INFO juju.worker.uniter awaiting error resolution for "leader-settings-changed" hook
unit-flannel-1: 15:32:02 INFO juju.worker.uniter awaiting error resolution for "leader-settings-changed" hook
unit-flannel-1: 15:32:02 INFO unit.flannel/1.juju-log Reactive main running for hook leader-settings-changed
```

**Comment by chuckbutler** [comment]
Yep, looks like there's some very unfriendly code in there thats not accounting for two scenarios

1) the flannel daemon is not running (EG: A reboot happened and the systemd unit file didn't restart the service)
2) any other thing that might have happened to the daemon, and the charm isn't attempting a restart. 

This should be  a simple fix to cut for the next cycle. Thanks for filing it @simonklb. I'll circle back on this one over this week and try to get a patch ready for release.

**Comment by simonklb** [comment]
When can we expect the fix to hit the charmstore?

**Comment by chuckbutler** [comment]
its already in the store in the edge channel. It will be promoted to stable with the 1.5.2 release.

**Comment by chuckbutler** [comment]
This went out with last weeks 1.5.2 publication. Thanks for filing the bug and adding detailed information
