### ISSUE TITLE
charm-flannel is giving python errors 

### ISSUE THREAD

**Issue by dimthe** [juju-solutions/charm-flannel#52]
Hello
Following this official how to : https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Running-CDK-in-a-restricted-environment everything is working fine and a cluster builds with no errors during the deployment .  
After a while juju status will show errors about flannel not starting , as seen below 

```
`juju status
Model    Controller  Cloud/Region  Version  SLA          Timestamp
default  controller  auvious       2.4.7    unsupported  13:29:41Z

App                    Version  Status   Scale  Charm                  Store  Rev  OS      Notes
easyrsa                3.0.1    active       1  easyrsa                local    0  ubuntu
etcd                   2.3.8    active       3  etcd                   local    0  ubuntu
flannel                         error        5  flannel                local    0  ubuntu
kubeapi-load-balancer  1.10.3   active       1  kubeapi-load-balancer  local    0  ubuntu
kubernetes-master      1.12.2   waiting      2  kubernetes-master      local    0  ubuntu
kubernetes-worker      1.12.2   waiting      3  kubernetes-worker      local    0  ubuntu

Unit                      Workload  Agent  Machine  Public address  Ports     Message
easyrsa/0*                active    idle   8        10.100.1.209              Certificate Authority connected.
etcd/0*                   active    idle   5        10.100.1.206    2379/tcp  Healthy with 3 known peers
etcd/1                    active    idle   6        10.100.1.207    2379/tcp  Healthy with 3 known peers
etcd/2                    active    idle   7        10.100.1.208    2379/tcp  Healthy with 3 known peers
kubeapi-load-balancer/0*  active    idle   9        10.100.1.210    443/tcp   Loadbalancer ready.
kubernetes-master/0*      waiting   idle   3        10.100.1.204              Waiting for CNI plugins to become available
  flannel/0*              error     idle            10.100.1.204              hook failed: "install"
kubernetes-master/1       waiting   idle   4        10.100.1.205              Waiting for CNI plugins to become available
  flannel/1               error     idle            10.100.1.205              hook failed: "install"
kubernetes-worker/0*      waiting   idle   0        10.100.1.201              Waiting for cluster DNS.
  flannel/2               error     idle            10.100.1.201              hook failed: "install"
kubernetes-worker/1       waiting   idle   1        10.100.1.202              Waiting for cluster DNS.
  flannel/4               error     idle            10.100.1.202              hook failed: "install"
kubernetes-worker/2       waiting   idle   2        10.100.1.203              Waiting for cluster DNS.
  flannel/3               error     idle            10.100.1.203              hook failed: "install"

Entity  Meter status  Message
model   amber         user verification pending

Machine  State    DNS           Inst id              Series  AZ  Message
0        started  10.100.1.201  manual:10.100.1.201  xenial      Manually provisioned machine
1        started  10.100.1.202  manual:10.100.1.202  xenial      Manually provisioned machine
2        started  10.100.1.203  manual:10.100.1.203  xenial      Manually provisioned machine
3        started  10.100.1.204  manual:10.100.1.204  xenial      Manually provisioned machine
4        started  10.100.1.205  manual:10.100.1.205  xenial      Manually provisioned machine
5        started  10.100.1.206  manual:10.100.1.206  xenial      Manually provisioned machine
6        started  10.100.1.207  manual:10.100.1.207  xenial      Manually provisioned machine
7        started  10.100.1.208  manual:10.100.1.208  xenial      Manually provisioned machine
8        started  10.100.1.209  manual:10.100.1.209  xenial      Manually provisioned machine
9        started  10.100.1.210  manual:10.100.1.210  xenial      Manually provisioned machine`
```

logs show these errors 

```
unit-flannel-2: 02:48:03 ERROR unit.flannel/2.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flannel-2/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-flannel-2/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-flannel-2/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-flannel-2/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-flannel-2/charm/reactive/flannel.py", line 67, in install_flannel_binaries
    check_call(install)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['install', '-v', '-D', '/var/lib/juju/agents/unit-flannel-2/charm/files/flannel/flannel', '/opt/cni/bin/flannel']' returned non-zero exit status 1

unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install Traceback (most recent call last):
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install   File "/var/lib/juju/agents/unit-flannel-2/charm/hooks/install", line 22, in <module>
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install     main()
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install   File "/var/lib/juju/agents/unit-flannel-2/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install     bus.dispatch(restricted=restricted_mode)
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install   File "/var/lib/juju/agents/unit-flannel-2/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install     _invoke(other_handlers)
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install   File "/var/lib/juju/agents/unit-flannel-2/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install     handler.invoke()
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install   File "/var/lib/juju/agents/unit-flannel-2/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install     self._action(*args)
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install   File "/var/lib/juju/agents/unit-flannel-2/charm/reactive/flannel.py", line 67, in install_flannel_binaries
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install     check_call(install)
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install     raise CalledProcessError(retcode, cmd)
unit-flannel-2: 02:48:03 DEBUG unit.flannel/2.install subprocess.CalledProcessError: Command '['install', '-v', '-D', '/var/lib/juju/agents/unit-flannel-2/charm/files/flannel/flannel', '/opt/cni/bin/flannel']' returned non-zero exit status 1
unit-flannel-2: 02:48:03 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1
```

looking at this line 
 Command '['install', '-v', '-D', '/var/lib/juju/agents/unit-flannel-2/charm/files/flannel/flannel', '/opt/cni/bin/flannel']'

should this be flannel or flanneld ?  because ihave flanneld

 ls /var/lib/juju/agents/unit-flannel-2/charm/files/flannel/
BUILD_INFO  etcdctl  flanneld
ubuntu@j1:~$

and there is no flannel in opt/cni/bin
```
opt/cni/bin$ ls
ubuntu@j4:/opt/cni/bin$
```

i tried the same procedure using the offline-how to to build the charms using shrinkwrap.py  for kubernetes-core this time and i have the same exact flannel errors on both clusters

is there a workaround till this gets fixed ? thanks

**Comment by Cynerva** [comment]
Yeah, we've encountered this issue internally as well. I'm currently working on a fix. Sorry about this!

**Comment by dimthe** [comment]
let me be your beta tester  .

**Comment by Cynerva** [comment]
This should be fixed now. Can you please try another deployment and let me know if you hit the problem again?

**Comment by Cynerva** [comment]
To explain, the problem was in the stable bundle definitions for `canonical-kubernetes`, `kubernetes-core`, and other bundles that we maintain as well. Due to some quirks in the way the charm store handles charm resources, Juju ended up deploying the flannel charm from the stable channel, but with resource revisions from the edge channel. The older charm code was expecting some files to exist in the resources that no longer exist in the newer ones.

For a quick fix, I manually patched the bundles to include resource revisions for the flannel, calico, and canal charms. This ensures that the correct resource gets pulled in when the bundle is deployed.

For a long-term fix, I've created https://github.com/juju-solutions/bundle-canonical-kubernetes/pull/701 which will ensure that we pin resource revisions across the board for all bundles that we build from now on.

**Comment by dimthe** [comment]
hello @Cynerva 

i think i am getting the same errors 

i started from scratch . New machines and git cloned 

`git clone https://github.com/juju-solutions/cdk-shrinkwrap.git`
i then built it like so : `./shrinkwrap.py kubernetes-core --channel stable`

the produced deploy script finishes with no errors

```

~/cdk-shrinkwrap/kubernetes-core-stable-2018-12-03-21-22-24$ ./deploy.sh
+ MACHINES='1 5 6 7'
+ set +x
+ for machine in '$MACHINES'
+ juju scp resources/core.snap 1:
+ juju run --machine 1 'sudo snap install --dangerous /home/ubuntu/core.snap'
2018-12-03T22:17:06Z INFO Waiting for restart...
core 16-2.36.1 installed
sudo: unable to resolve host juju-k8s-core2
+ for machine in '$MACHINES'
+ juju scp resources/core.snap 5:
+ juju run --machine 5 'sudo snap install --dangerous /home/ubuntu/core.snap'
2018-12-03T22:17:29Z INFO Waiting for restart...
core 16-2.36.1 installed
sudo: unable to resolve host juju-k8s-core3
+ for machine in '$MACHINES'
+ juju scp resources/core.snap 6:
+ juju run --machine 6 'sudo snap install --dangerous /home/ubuntu/core.snap'
2018-12-03T22:17:41Z INFO Waiting for restart...
core 16-2.36.1 installed
sudo: unable to resolve host juju-k8s-core4
+ for machine in '$MACHINES'
+ juju scp resources/core.snap 7:
+ juju run --machine 7 'sudo snap install --dangerous /home/ubuntu/core.snap'
2018-12-03T22:17:55Z INFO Waiting for restart...
core 16-2.36.1 installed
sudo: unable to resolve host juju-k8s-core5
+ MACHINE_LIST='1 5 6 7'
+ juju deploy --series=xenial -n 1 --resource easyrsa=./resources/easyrsa/easyrsa.tgz --to 1 ./charms/easyrsa
Deploying charm "local:xenial/easyrsa-2".
+ juju deploy --series=xenial -n 1 --resource etcd=./resources/etcd/etcd.snap --resource snapshot=./resources/etcd/snapshot.gz --to 5 ./charms/etcd
Deploying charm "local:xenial/etcd-1".
+ juju deploy --series=xenial -n 1 --resource cni-amd64=./resources/kubernetes-worker/cni-amd64.tgz --resource cni-arm64=./resources/kubernetes-worker/cni-arm64.tgz --resource cni-s390x=./resources/kubernetes-worker/cni-s390x.tgz --resource kube-proxy=./resources/kubernetes-worker/kube-proxy.snap --resource kubectl=./resources/kubernetes-worker/kubectl.snap --resource kubelet=./resources/kubernetes-worker/kubelet.snap --to 6 ./charms/kubernetes-worker
Deploying charm "local:xenial/kubernetes-worker-1".
+ juju deploy --series=xenial --resource flannel-amd64=./resources/flannel/flannel-amd64.gz --resource flannel-arm64=./resources/flannel/flannel-arm64.gz --resource flannel-s390x=./resources/flannel/flannel-s390x.gz ./charms/flannel
Deploying charm "local:xenial/flannel-1".
+ juju deploy --series=xenial -n 1 --resource cdk-addons=./resources/kubernetes-master/cdk-addons.snap --resource kube-apiserver=./resources/kubernetes-master/kube-apiserver.snap --resource kube-controller-manager=./resources/kubernetes-master/kube-controller-manager.snap --resource kube-proxy=./resources/kubernetes-master/kube-proxy.snap --resource kube-scheduler=./resources/kubernetes-master/kube-scheduler.snap --resource kubectl=./resources/kubernetes-master/kubectl.snap --to 7 ./charms/kubernetes-master
Deploying charm "local:xenial/kubernetes-master-0".
+ juju relate kubernetes-master:kube-api-endpoint kubernetes-worker:kube-api-endpoint
+ juju relate kubernetes-master:kube-control kubernetes-worker:kube-control
+ juju relate kubernetes-master:certificates easyrsa:client
+ juju relate kubernetes-master:etcd etcd:db
+ juju relate kubernetes-worker:certificates easyrsa:client
+ juju relate etcd:certificates easyrsa:client
+ juju relate flannel:etcd etcd:db
+ juju relate flannel:cni kubernetes-master:cni
+ juju relate flannel:cni kubernetes-worker:cni
```


but juju status has flannel in an error state


```

App                Version  Status   Scale  Charm              Store  Rev  OS      Notes
easyrsa            3.0.1    active       1  easyrsa            local    2  ubuntu
etcd               2.3.8    active       1  etcd               local    1  ubuntu
flannel                     error        2  flannel            local    1  ubuntu
kubernetes-master  1.12.2   waiting      1  kubernetes-master  local    0  ubuntu
kubernetes-worker  1.12.2   waiting      1  kubernetes-worker  local    1  ubuntu

Unit                  Workload  Agent  Machine  Public address  Ports     Message
easyrsa/1*            active    idle   1        10.100.1.212              Certificate Authority connected.
etcd/1*               active    idle   5        10.100.1.213    2379/tcp  Healthy with 1 known peer
kubernetes-master/0*  waiting   idle   7        10.100.1.215              Waiting for CNI plugins to become available
  flannel/0*          error     idle            10.100.1.215              hook failed: "install"
kubernetes-worker/1*  waiting   idle   6        10.100.1.214              Waiting for cluster DNS.
  flannel/1           error     idle            10.100.1.214              hook failed: "install"

Machine  State    DNS           Inst id              Series  AZ  Message
1        started  10.100.1.212  manual:10.100.1.212  xenial      Manually provisioned machine
5        started  10.100.1.213  manual:10.100.1.213  xenial      Manually provisioned machine
6        started  10.100.1.214  manual:10.100.1.214  xenial      Manually provisioned machine
7        started  10.100.1.215  manual:10.100.1.215  xenial      Manually provisioned machine

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       etcd:certificates                    tls-certificates  regular
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular
etcd:cluster                         etcd:cluster                         etcd              peer
etcd:db                              flannel:etcd                         etcd              regular
etcd:db                              kubernetes-master:etcd               etcd              regular
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate
kubernetes-master:kube-api-endpoint  kubernetes-worker:kube-api-endpoint  http              regular
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate

```


in logs i see these



```
unit-flannel-0: 22:30:51 ERROR unit.flannel/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-flannel-0/charm/reactive/flannel.py", line 67, in install_flannel_binaries
    check_call(install)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['install', '-v', '-D', '/var/lib/juju/agents/unit-flannel-0/charm/files/flannel/flannel', '/opt/cni/bin/flannel']' returned non-zero exit status 1

unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install Traceback (most recent call last):
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install   File "/var/lib/juju/agents/unit-flannel-0/charm/hooks/install", line 22, in <module>
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install     main()
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install   File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 73, in main
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install     bus.dispatch(restricted=restricted_mode)
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install   File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 390, in dispatch
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install     _invoke(other_handlers)
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install   File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 359, in _invoke
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install     handler.invoke()
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install   File "/var/lib/juju/agents/unit-flannel-0/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 181, in invoke
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install     self._action(*args)
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install   File "/var/lib/juju/agents/unit-flannel-0/charm/reactive/flannel.py", line 67, in install_flannel_binaries
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install     check_call(install)
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install     raise CalledProcessError(retcode, cmd)
unit-flannel-0: 22:30:51 DEBUG unit.flannel/0.install subprocess.CalledProcessError: Command '['install', '-v', '-D', '/var/lib/juju/agents/unit-flannel-0/charm/files/flannel/flannel', '/opt/cni/bin/flannel']' returned non-zero exit status 1
unit-flannel-0: 22:30:51 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1
unit-flannel-0: 22:30:51 DEBUG juju.machinelock machine lock released for uniter (run install hook)
unit-flannel-0: 22:30:51 DEBUG juju.worker.uniter.operation lock released
unit-flannel-0: 22:30:51 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-flannel-0: 22:30:51 DEBUG juju.worker.uniter [AGENT-STATUS] error: hook failed: "install"
^C
```

**Comment by dimthe** [comment]
using your changes in the script 

```
   # Get the charm resources metadata.
        charm = id.rpartition('-')[0]
        resp = requests.get(
            'https://api.jujucharms.com/charmstore/v5/%s/meta/resources' % charm,
            params={'channel': args.channel}
        )
        resources = json.loads(resp.text)
        bundle['applications'][appname]['resources'] = resources
```

which i   wget https://raw.githubusercontent.com/juju-solutions/cdk-shrinkwrap/3e26ee163e0a9f5bea6d6a13d8eb4a378e48ad38/shrinkwrap.py

and executed it , i saw that it gets flannel-339 as seen below . Is this correct?

```
./shrinkwrap.py kubernetes-core --channel stable
kubernetes-master
    Downloading ~containers/kubernetes-master-522...
    Downloading resource cdk-addons.snap from snap store...
    Downloading resource kube-apiserver.snap from snap store...
    Downloading resource kube-controller-manager.snap from snap store...
    Downloading resource kube-proxy.snap from snap store...
    Downloading resource kube-scheduler.snap from snap store...
    Downloading resource kubectl.snap from snap store...
easyrsa
    Downloading ~containers/easyrsa-185...
    Downloading resource easyrsa.tgz from charm store revision 5...
etcd
    Downloading ~containers/etcd-319...
    Downloading resource etcd.snap from snap store...
    Downloading resource snapshot.gz from charm store revision 0...
flannel
    Downloading ~containers/flannel-339...
    Downloading resource flannel-amd64.gz from charm store revision 3...
    Downloading resource flannel-arm64.gz from charm store revision 1...
    Downloading resource flannel-s390x.gz from charm store revision 3...
kubernetes-worker
    Downloading ~containers/kubernetes-worker-378...
    Downloading resource cni-amd64.tgz from charm store revision 2...
    Downloading resource cni-arm64.tgz from charm store revision 1...
    Downloading resource cni-s390x.tgz from charm store revision 2...
    Downloading resource kube-proxy.snap from snap store...
    Downloading resource kubectl.snap from snap store...
    Downloading resource kubelet.snap from snap store...
Writing deploy scripts...
    deploy.sh
    kubernetes-core-stable-2018-12-03-23-51-01/add-unit-kubernetes-master.sh
    kubernetes-core-stable-2018-12-03-23-51-01/add-unit-easyrsa.sh
    kubernetes-core-stable-2018-12-03-23-51-01/add-unit-etcd.sh
    kubernetes-core-stable-2018-12-03-23-51-01/add-unit-flannel.sh
    kubernetes-core-stable-2018-12-03-23-51-01/add-unit-kubernetes-worker.sh
Downloading the core snap...
Done.
```

**Comment by dimthe** [comment]
Hello @Cynerva 

using this 

wget https://raw.githubusercontent.com/juju-solutions/cdk-shrinkwrap/3e26ee163e0a9f5bea6d6a13d8eb4a378e48ad38/shrinkwrap.py

i see it downloaded flannel-339 

```

./shrinkwrap.py kubernetes-core --channel stable
flannel
    Downloading ~containers/flannel-339...
    Downloading resource flannel-amd64.gz from charm store revision 3...
    Downloading resource flannel-arm64.gz from charm store revision 1...
    Downloading resource flannel-s390x.gz from charm store revision 3...
kubernetes-worker
    Downloading ~containers/kubernetes-worker-378...
    Downloading resource cni-amd64.tgz from charm store revision 2...
    Downloading resource cni-arm64.tgz from charm store revision 1...
    Downloading resource cni-s390x.tgz from charm store revision 2...
    Downloading resource kube-proxy.snap from snap store...
    Downloading resource kubectl.snap from snap store...
    Downloading resource kubelet.snap from snap store...
kubernetes-master
    Downloading ~containers/kubernetes-master-522...
    Downloading resource cdk-addons.snap from snap store...
    Downloading resource kube-apiserver.snap from snap store...
    Downloading resource kube-controller-manager.snap from snap store...
    Downloading resource kube-proxy.snap from snap store...
    Downloading resource kube-scheduler.snap from snap store...
    Downloading resource kubectl.snap from snap store...
etcd
    Downloading ~containers/etcd-319...
    Downloading resource etcd.snap from snap store...
    Downloading resource snapshot.gz from charm store revision 0...
easyrsa
    Downloading ~containers/easyrsa-185...
    Downloading resource easyrsa.tgz from charm store revision 5...
Writing deploy scripts...
    deploy.sh
    kubernetes-core-stable-2018-12-04-10-58-58/add-unit-flannel.sh
    kubernetes-core-stable-2018-12-04-10-58-58/add-unit-kubernetes-worker.sh
    kubernetes-core-stable-2018-12-04-10-58-58/add-unit-kubernetes-master.sh
    kubernetes-core-stable-2018-12-04-10-58-58/add-unit-etcd.sh
    kubernetes-core-stable-2018-12-04-10-58-58/add-unit-easyrsa.sh
Downloading the core snap...
Done.
```


is this correct?

**Comment by dimthe** [comment]
to answer my own question above , it is correct

kubernete-core was successfully deployed . 
Another bug with the produced deploy script is that it defaults charms to a bionic release. As a workaround i had to edit each deploy line to say --series=xenial   . I had opened an issue about this here https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/700


as for the flannel charm , it all looks good. Now i have to try it with canonical-kubernetes





```
easyrsa            3.0.1    active      1  easyrsa            local    0  ubuntu
etcd               2.3.8    active      1  etcd               local    0  ubuntu
flannel            0.10.0   active      2  flannel            local    0  ubuntu
kubernetes-master  1.12.2   active      1  kubernetes-master  local    0  ubuntu
kubernetes-worker  1.12.2   active      1  kubernetes-worker  local    0  ubuntu

Unit                  Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*            active    idle   3        10.100.1.215                    Certificate Authority connected.
etcd/0*               active    idle   0        10.100.1.213    2379/tcp        Healthy with 1 known peer
kubernetes-master/0*  active    idle   2        10.100.1.214    6443/tcp        Kubernetes master running.
  flannel/0*          active    idle            10.100.1.214                    Flannel subnet 10.1.19.1/24
kubernetes-worker/0*  active    idle   1        10.100.1.212    80/tcp,443/tcp  Kubernetes worker running.
  flannel/1           active    idle            10.100.1.212                    Flannel subnet 10.1.17.1/24

Entity  Meter status  Message
model   amber         user verification pending

Machine  State    DNS           Inst id              Series  AZ  Message
0        started  10.100.1.213  manual:10.100.1.213  xenial      Manually provisioned machine
1        started  10.100.1.212  manual:10.100.1.212  xenial      Manually provisioned machine
2        started  10.100.1.214  manual:10.100.1.214  xenial      Manually provisioned machine
3        started  10.100.1.215  manual:10.100.1.215  xenial      Manually provisioned machine

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       etcd:certificates                    tls-certificates  regular
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular
etcd:cluster                         etcd:cluster                         etcd              peer
etcd:db                              flannel:etcd                         etcd              regular
etcd:db                              kubernetes-master:etcd               etcd              regular
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate
kubernetes-master:kube-api-endpoint  kubernetes-worker:kube-api-endpoint  http              regular
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate 
```

**Comment by Cynerva** [comment]
> i see it downloaded flannel-339 ... is this correct?

Yep, the charm and resource revisions from that output look correct. Thanks for following up.

**Comment by dimthe** [comment]
@Cynerva 

canonical-kuberentes looks ok  too so i think the issue should be closed now 



```
App                    Version  Status  Scale  Charm                  Store  Rev  OS      Notes
easyrsa                3.0.1    active      1  easyrsa                local    0  ubuntu
etcd                   2.3.8    active      3  etcd                   local    0  ubuntu
flannel                0.10.0   active      5  flannel                local    0  ubuntu
kubeapi-load-balancer  1.10.3   active      1  kubeapi-load-balancer  local    0  ubuntu
kubernetes-master      1.12.3   active      2  kubernetes-master      local    0  ubuntu
kubernetes-worker      1.12.3   active      3  kubernetes-worker      local    0  ubuntu

Unit                      Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*                active    idle   6        10.100.1.207                    Certificate Authority connected.
etcd/0                    active    idle   7        10.100.1.208    2379/tcp        Healthy with 3 known peers
etcd/1*                   active    idle   8        10.100.1.209    2379/tcp        Healthy with 3 known peers
etcd/2                    active    idle   9        10.100.1.210    2379/tcp        Healthy with 3 known peers
kubeapi-load-balancer/0*  active    idle   0        10.100.1.201    443/tcp         Loadbalancer ready.
kubernetes-master/0*      active    idle   4        10.100.1.205    6443/tcp        Kubernetes master running.
  flannel/2               active    idle            10.100.1.205                    Flannel subnet 10.1.65.1/24
kubernetes-master/1       active    idle   5        10.100.1.206    6443/tcp        Kubernetes master running.
  flannel/4               active    idle            10.100.1.206                    Flannel subnet 10.1.15.1/24
kubernetes-worker/0       active    idle   1        10.100.1.202    80/tcp,443/tcp  Kubernetes worker running.
  flannel/1               active    idle            10.100.1.202                    Flannel subnet 10.1.74.1/24
kubernetes-worker/1*      active    idle   2        10.100.1.203    80/tcp,443/tcp  Kubernetes worker running.
  flannel/0*              active    idle            10.100.1.203                    Flannel subnet 10.1.14.1/24
kubernetes-worker/2       active    idle   3        10.100.1.204    80/tcp,443/tcp  Kubernetes worker running.
  flannel/3               active    idle            10.100.1.204                    Flannel subnet 10.1.63.1/24

Entity  Meter status  Message
model   amber         user verification pending

Machine  State    DNS           Inst id              Series  AZ  Message
0        started  10.100.1.201  manual:10.100.1.201  xenial      Manually provisioned machine
1        started  10.100.1.202  manual:10.100.1.202  xenial      Manually provisioned machine
2        started  10.100.1.203  manual:10.100.1.203  xenial      Manually provisioned machine
3        started  10.100.1.204  manual:10.100.1.204  xenial      Manually provisioned machine
4        started  10.100.1.205  manual:10.100.1.205  xenial      Manually provisioned machine
5        started  10.100.1.206  manual:10.100.1.206  xenial      Manually provisioned machine
6        started  10.100.1.207  manual:10.100.1.207  xenial      Manually provisioned machine
7        started  10.100.1.208  manual:10.100.1.208  xenial      Manually provisioned machine
8        started  10.100.1.209  manual:10.100.1.209  xenial      Manually provisioned machine
9        started  10.100.1.210  manual:10.100.1.210  xenial      Manually provisioned machine


```

**Comment by Cynerva** [comment]
Thanks. I'm closing this, but I've opened up follow-up issues:
* https://github.com/juju/python-libjuju/issues/273
* https://github.com/juju-solutions/cdk-shrinkwrap/issues/10
